// xml/xml.ts
//
// JS wrapper for the generated wasm module (xml/_wasm/xml_xml.mjs). Trees
// cross the wasm boundary as JSON strings (one JSON.parse is far cheaper
// than building the tree through per-node FFI calls).
//
// Shared types are imported from @std/xml — never redeclared — so this
// package is a true drop-in for @std/xml consumers. The only types declared
// locally (via the wasm module's typescript_custom_section) are
// XmlValidationIssue and XmlValidationResult, which @std/xml does not have.
//
// The wrapper's added value:
//   1. Re-throwing wasm errors as @std/xml's actual XmlSyntaxError class
//      (the wasm module can only throw plain `Error` — it cannot construct
//      JS classes; @std/xml's XmlSyntaxError has a public constructor taking
//      (message, position), so we use it directly).
//   2. A std-shaped public surface:
//        parse(xml, options?)    → XmlDocument
//        stringify(doc, opts?)   → string
//        validate(doc, schema)   → { value: XmlDocument } | { issues: Issue[] }
//   3. xsdSchema(schema) → a Standard Schema v1 entity
//      (https://standardschema.dev): issues carry Standard-Schema-shaped
//      `path` segments (element names + sibling indices) derived from the
//      validator's line/column positions, so any Standard Schema consumer
//      can use @stdext/xml schemas.

import {
  checkTree as wasmCheckTree,
  parse as wasmParse,
  stringify as wasmStringify,
  XmlSchema as WasmXmlSchema,
} from "./_wasm/xml_xml.mjs";
// Validation types generated by the wasm module (not available in @std/xml):
import type { XmlValidationResult } from "./_wasm/xml_xml.mjs";
import type {
  ParseOptions,
  StringifyOptions,
  XmlDocument,
  XmlNode,
} from "@std/xml";
import type { StandardSchemaV1 } from "@standard-schema/spec";
import { XmlSyntaxError } from "@std/xml";
import { isObject } from "@stdext/validation";
import { SchemaError } from "@standard-schema/utils";
import {
  XmlDeclaration,
  XmlElement,
} from "https://jsr.io/@std/xml/0.2.0/types.ts";

// Shared types come straight from @std/xml and are re-exported as-is.
// The document tree produced by the wasm `parse` is structurally identical,
// so these are not casts of convenience — they are the same types.
export type {
  ParseOptions,
  StringifyOptions,
  XmlCDataNode,
  XmlCommentNode,
  XmlDeclaration,
  XmlDocument,
  XmlElement,
  XmlName,
  XmlNode,
  XmlPosition,
  XmlTextNode,
} from "@std/xml";

// Validation types generated by the wasm module. These reference the
// Standard Schema spec types (`@standard-schema/spec`) — the spec's own
// interfaces are NEVER redeclared here.
export type { XmlValidationResult } from "./_wasm/xml_xml.mjs";

// Re-export the spec types so consumers of @stdext/xml don't have to
// depend on @standard-schema/spec to spell the public surface.
export type { StandardSchemaV1 } from "@standard-schema/spec";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

// /**
//  * @std/xml creates attribute maps with a null prototype (so that attribute
//  * names like "__proto__" or "constructor" cannot collide with Object
//  * prototype members). JSON.parse produces plain objects, so swap their
//  * prototype in place to match @std/xml's output.
//  */
// function fixAttributePrototypes(node: XmlNode): void {
//   if (node.type !== "element") return;
//   Object.setPrototypeOf(node.attributes, null);
//   for (const child of node.children) fixAttributePrototypes(child);
// }

// const POSITION_RE = / at line (\d+), column (\d+)$/;

// /** Convert a wasm `Error` into @std/xml's `XmlSyntaxError`. */
// function toXmlSyntaxError(error: unknown): unknown {
//   if (!(error instanceof Error) || error instanceof XmlSyntaxError) {
//     return error;
//   }
//   const match = error.message.match(POSITION_RE);
//   // 0/0/0 is @std/xml's sentinel for "position unavailable"
//   return new XmlSyntaxError(
//     match ? error.message.slice(0, match.index) : error.message,
//     {
//       line: Number(match?.[1] ?? 0),
//       column: Number(match?.[2] ?? 0),
//       offset: 0,
//     },
//   );
// }

// /** Re-throw a wasm `Error` as @std/xml's `XmlSyntaxError`. */
// function rethrowAsXmlSyntaxError(error: unknown): never {
//   throw toXmlSyntaxError(error);
// }

// /** Whether `value` is shaped like an {@linkcode XmlDocument}. */
// function isXmlDocument(value: unknown): value is XmlDocument {
//   return isObject(value) && "root" in value && isObject(value.root);
// }

// /** Compile an XSD schema given as XML text or as a document tree. */
// function compileSchema(schema: string | XmlDocument): WasmXmlSchema {
//   try {
//     return typeof schema === "string"
//       ? new WasmXmlSchema(schema)
//       : WasmXmlSchema.fromTree(JSON.stringify(schema));
//   } catch (error) {
//     rethrowAsXmlSyntaxError(error);
//   }
// }

// /** Validate a document against a compiled schema. */
// function validateWith(
//   schema: WasmXmlSchema,
//   document: string | XmlDocument,
// ): XmlValidationResult {
//   try {
//     if (typeof document === "string") {
//       const result: XmlValidationResult = JSON.parse(
//         schema.validate(document),
//       );
//       if (result.issues === undefined) {
//         fixAttributePrototypes(result.value.root);
//       }
//       return result;
//     }
//     // The caller already holds the tree: on success it is returned as-is.
//     const issues = schema.validateTree(JSON.stringify(document));
//     return issues === undefined
//       ? { value: document }
//       : { issues: JSON.parse(issues) };
//   } catch (error) {
//     rethrowAsXmlSyntaxError(error);
//   }
// }

// /** Convert a well-formedness error into a Standard Schema issue. */
// function syntaxErrorToIssue(error: XmlSyntaxError): StandardSchemaV1.Issue {
//   const issue = { message: error.message };
//   return error.line === 0 ? issue : {
//     ...issue,
//     line: error.line,
//     column: error.column,
//   } as StandardSchemaV1.Issue;
// }

// // ---------------------------------------------------------------------------
// // Public API
// // ---------------------------------------------------------------------------

// /**
//  * Parses an XML string into a document tree.
//  *
//  * Drop-in compatible with @std/xml's `parse`: the returned object has the
//  * identical shape (`{ declaration?, root }`), and the options follow
//  * @std/xml's `ParseOptions`. Supported options: `ignoreWhitespace`,
//  * `ignoreComments`, `disallowDoctype` (default true), `maxDepth`,
//  * `trackPosition` (default true; affects the declaration's position
//  * fields). `maxAttributes` and `xmlVersion` are accepted and ignored.
//  *
//  * @example Usage
//  * ```ts
//  * import { parse } from "@stdext/xml";
//  * import { assertEquals } from "@std/assert";
//  *
//  * const doc = parse(`<root id="1"><child/></root>`);
//  * assertEquals(doc.root.name.local, "root");
//  * assertEquals(doc.root.attributes["id"], "1");
//  * ```
//  *
//  * @param xml The XML string to parse.
//  * @param options Options for configuring the parser.
//  * @returns The parsed document.
//  * @throws {XmlSyntaxError} If the XML is malformed or has no root element.
//  */
// export function parse(xml: string, options?: ParseOptions): XmlDocument {
//   try {
//     const doc: XmlDocument = JSON.parse(
//       wasmParse(xml, JSON.stringify(options ?? {})),
//     );
//     fixAttributePrototypes(doc.root);
//     return doc;
//   } catch (error) {
//     rethrowAsXmlSyntaxError(error);
//   }
// }

// /**
//  * Serializes a document tree back to an XML string.
//  *
//  * Drop-in compatible with @std/xml's `stringify`: `indent` pretty-prints,
//  * and `declaration` (default `true`) includes the XML declaration when the
//  * input document has one.
//  *
//  * @example Usage
//  * ```ts
//  * import { parse, stringify } from "@stdext/xml";
//  *
//  * const doc = parse("<root><child/></root>");
//  * stringify(doc);                    // "<root><child/></root>"
//  * stringify(doc, { indent: "  " });  // pretty-printed
//  * ```
//  *
//  * @param doc The document tree to serialize.
//  * @param options Serialization options.
//  * @returns The serialized XML string.
//  * @throws {SyntaxError} If the input is not a valid XmlDocument object.
//  */
// export function stringify(
//   doc: XmlDocument,
//   options?: StringifyOptions,
// ): string {
//   return wasmStringify(JSON.stringify(doc), JSON.stringify(options ?? {}));
// }

// /**
//  * Validates a document against an XSD schema.
//  *
//  * Both `schema` and `document` accept either an XML string or the plain
//  * document object (the same shape `parse` produces). To validate several
//  * documents against the same schema, use {@linkcode XmlValidator}, which
//  * compiles the schema only once.
//  *
//  * Returns the Standard Schema `Result` union (https://standardschema.dev):
//  *   - success: `{ value: XmlDocument }` — `issues` is undefined (falsy).
//  *     For a document tree input, `value` is that same tree.
//  *   - failure: `{ issues: StandardSchemaV1.Issue[] }` — no `value`
//  *
//  * Each issue carries `message` and, best-effort, `path` (the chain of
//  * enclosing element names with 0-based indices for repeated siblings).
//  * Consumers can apply `@standard-schema/utils` helpers (`getDotPath`,
//  * `SchemaError`) directly to the result — the issue shape is the spec's own.
//  *
//  * Note: a schema that is not well-formed or is an invalid XSD *throws*
//  * (`XmlSyntaxError`) — that is a schema-authoring error, not a document
//  * issue.
//  *
//  * @example Usage
//  * ```ts
//  * import { validate } from "@stdext/xml";
//  * import { assert } from "@std/assert";
//  *
//  * const xsd = `<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
//  *   <xs:element name="age" type="xs:positiveInteger"/>
//  * </xs:schema>`;
//  *
//  * const result = validate(xsd, "<age>25</age>");
//  * assert(result.issues === undefined); // success
//  * result.value.root.name.local; // "age"
//  * ```
//  *
//  * @param schema The XSD schema to validate against (XML string or tree).
//  * @param document The document to validate (XML string or document tree).
//  * @returns The Standard Schema result: `{ value }` or `{ issues }`.
//  * @throws {XmlSyntaxError} If the document or schema is not well-formed XML,
//  * or the schema is an invalid XSD.
//  */
// export function validate(
//   schema: string | XmlDocument,
//   document: string | XmlDocument,
// ): XmlValidationResult {
//   const compiled = compileSchema(schema);
//   try {
//     return validateWith(compiled, document);
//   } finally {
//     compiled.free();
//   }
// }

export class XML implements XmlDocument {
  #document: XmlDocument;

  get document(): XmlDocument {
    return this.#document;
  }

  get declaration(): XmlDeclaration | undefined {
    return this.document.declaration;
  }
  get root(): XmlElement {
    return this.document.root;
  }

  constructor(document: XmlDocument) {
    this.#document = document;
  }

  static safeParse(
    document: string | XmlDocument,
    options?: ParseOptions,
  ): StandardSchemaV1.Result<XML> {
    const res = typeof document === "string"
      ? wasmParse(document, options)
      : document;

    return {
      value: res.value ? new XML(res.value) : undefined,
      issues: res.issues?.map((i) => ({ message: i.message, path: i.path })),
    };
  }

  static parse(
    document: string | XmlDocument,
    options?: ParseOptions,
  ): XML {
    const res = this.safeParse(document, options);

    if (res.issues) {
      throw new SchemaError(res.issues);
    }

    return new XML(res.value);
  }

  stringify(options?: StringifyOptions): string {
    return wasmStringify(this.#document, options);
  }

  validate(
    schema: XMLValidator | XmlDocument | string,
  ): StandardSchemaV1.Result<XmlDocument> {
    if (schema instanceof XMLValidator) {
      return schema.validate(this.#document);
    }

    return new XMLValidator(schema).validate(this.#document);
  }
}

/**
 * A compiled XSD schema, reusable for validating many documents.
 *
 * The schema is compiled once, in the constructor. The compiled schema
 * lives in wasm memory: it is released when the validator is garbage
 * collected, or immediately with `using` / `[Symbol.dispose]()`.
 *
 * @example Usage
 * ```ts
 * import { XmlValidator } from "@stdext/xml";
 * import { assert, assertThrows } from "@std/assert";
 *
 * using validator = new XmlValidator(`<xs:schema
 *   xmlns:xs="http://www.w3.org/2001/XMLSchema">
 *   <xs:element name="age" type="xs:positiveInteger"/>
 * </xs:schema>`);
 *
 * assert(validator.validate("<age>25</age>").issues === undefined);
 * assert(validator.validate("<age>-5</age>").issues !== undefined);
 * assertThrows(() => validator.parse("<age>-5</age>"));
 * ```
 */
export class XMLValidator {
  #schema: XML;

  /**
   * Compiles the schema.
   *
   * @param schema The XSD schema (XML string or document tree).
   * @throws {XmlSyntaxError} If the schema is not well-formed XML or is an
   * invalid XSD.
   */
  constructor(schema: string | XmlDocument) {
    this.#schema = XML.parse(schema);
  }

  /**
   * Validates a document against the schema.
   *
   * @param doc The document (XML string or document tree).
   * @returns The Standard Schema result: `{ value }` or `{ issues }`.
   * @throws {XmlSyntaxError} If the document is not well-formed XML.
   */
  validate(
    doc: string | XmlDocument | XML,
  ): StandardSchemaV1.Result<XmlDocument> {
    if (doc instanceof XML) {
      return doc.validate(this.#schema);
    }

    const parsedDoc = XML.safeParse(doc);

    if (parsedDoc.issues) {
      return { issues: parsedDoc.issues };
    }

    return parsedDoc.value.validate(this.#schema);
  }

  /**
   * Validates a document against the schema, and returns it as a tree.
   *
   * @param doc The document (XML string or document tree).
   * @returns The document tree.
   * @throws {SchemaError} If the document does not conform to the schema.
   * @throws {XmlSyntaxError} If the document is not well-formed XML.
   */
  parse(doc: string | XmlDocument | XML): XmlDocument {
    const result = this.validate(doc);
    if (result.issues) throw new SchemaError(result.issues);
    return result.value;
  }
}

// ---------------------------------------------------------------------------
// Standard Schema facade
// ---------------------------------------------------------------------------

/**
 * Create a Standard Schema v1 entity (https://standardschema.dev) for XML,
 * so it can be consumed by any Standard Schema-aware tool.
 *
 * The returned object's `~standard.validate(value)` accepts an XML string
 * or an XmlDocument and never throws for bad input — every problem is an
 * issue:
 *   - not a string or XmlDocument → issue
 *   - not well-formed XML → issue (with `line`/`column` when known)
 *   - with a schema: not conforming → the validator's issues, carrying
 *     best-effort `path`s (element names + sibling indices)
 *
 * On success it returns `{ value: XmlDocument }` (for a tree input, that
 * same tree). The schema is compiled once, when `xml()` is called; an
 * invalid schema throws there.
 *
 * @example Usage
 * ```ts
 * import { xml } from "@stdext/xml";
 * import { assert } from "@std/assert";
 *
 * const schema = xml(`<xs:schema
 *   xmlns:xs="http://www.w3.org/2001/XMLSchema">
 *   <xs:element name="age" type="xs:positiveInteger"/>
 * </xs:schema>`);
 *
 * const result = schema["~standard"].validate("<age>25</age>");
 * assert(!("issues" in result)); // success: result.value is the tree
 *
 * // Without a schema, only well-formedness is checked.
 * assert("issues" in xml()["~standard"].validate("<age>"));
 * ```
 *
 * @param schema The XSD schema (XML string or document tree). When omitted,
 * values are only checked for well-formedness.
 * @returns A Standard Schema v1 entity.
 * @throws {XmlSyntaxError} If the schema is not well-formed XML or is an
 * invalid XSD.
 */
export function xml(
  schema?: string | XmlDocument,
): StandardSchemaV1<string | XmlDocument, XmlDocument> {
  const validator = schema === undefined ? undefined : new XMLValidator(schema);

  return {
    "~standard": {
      version: 1,
      vendor: "@stdext/xml",
      validate: (value: unknown): StandardSchemaV1.Result<XmlDocument> => {
        try {
          // @ts-expect-error We expect this type error but it's fine since we handle it
          if (validator) return validator.validate(value);

          // @ts-expect-error We expect this type error but it's fine since we handle it
          return XML.parse(value);
        } catch (error) {
          if (error instanceof SchemaError) {
            return { issues: error.issues };
          }

          if (error instanceof Error) {
            return { issues: [{ message: error.message }] };
          }

          return { issues: [{ message: `Unknown error: ${error}` }] };
        }
      },
    },
  };
}
