// xml/xml.ts
//
// JS wrapper for the generated wasm module (xml/_wasm/xml_xml.mjs).
//
// Shared types are imported from @std/xml — never redeclared — so this
// package is a true drop-in for @std/xml consumers. The only types declared
// locally (via the wasm module's typescript_custom_section) are
// XmlValidationIssue and XmlValidationResult, which @std/xml does not have.
//
// The wrapper's added value:
//   1. Re-throwing wasm errors as @std/xml's actual XmlSyntaxError class
//      (the wasm module can only throw plain `Error` — it cannot construct
//      JS classes; @std/xml's XmlSyntaxError has a public constructor taking
//      (message, position), so we use it directly).
//   2. A std-shaped public surface:
//        parse(xml, options?)    → XmlDocument
//        stringify(doc, opts?)   → string
//        validate(doc, schema)   → { value: XmlDocument, issues: XmlValidationIssue[] }
//   3. compileSchema(schema) → a Standard Schema v1 entity
//      (https://standardschema.dev): issues carry Standard-Schema-shaped
//      `path` segments (element names + sibling indices) derived from the
//      validator's line/column positions, so any Standard Schema consumer
//      can use @stdext/xml schemas.

import {
  parse as wasmParse,
  stringify as wasmStringify,
  validate as wasmValidate,
} from "./_wasm/xml_xml.mjs";
// Validation types generated by the wasm module (not available in @std/xml):
import type { XmlValidationResult } from "./_wasm/xml_xml.mjs";
import type {
  ParseOptions,
  StringifyOptions,
  XmlDocument,
  XmlNode,
} from "@std/xml";
import type { StandardSchemaV1 } from "@standard-schema/spec";
import { XmlSyntaxError } from "@std/xml";
import { isObject } from "@stdext/validation";

// Shared types come straight from @std/xml and are re-exported as-is.
// The document tree produced by the wasm `parse` is structurally identical,
// so these are not casts of convenience — they are the same types.
export type {
  ParseOptions,
  StringifyOptions,
  XmlCDataNode,
  XmlCommentNode,
  XmlDeclaration,
  XmlDocument,
  XmlElement,
  XmlName,
  XmlNode,
  XmlPosition,
  XmlTextNode,
} from "@std/xml";

// Validation types generated by the wasm module. These reference the
// Standard Schema spec types (`@standard-schema/spec`) — the spec's own
// interfaces are NEVER redeclared here.
export type { XmlValidationResult } from "./_wasm/xml_xml.mjs";

// Re-export the spec types so consumers of @stdext/xml don't have to
// depend on @standard-schema/spec to spell the public surface.
export type { StandardSchemaV1 } from "@standard-schema/spec";

// ---------------------------------------------------------------------------
// Tree fixups
// ---------------------------------------------------------------------------

/**
 * @std/xml creates attribute maps with a null prototype (so that attribute
 * names like "__proto__" or "constructor" cannot collide with Object
 * prototype members). The wasm/serde boundary can only produce plain
 * objects, so rebuild the attribute maps here to be prototype-identical
 * to @std/xml's output. Key order is preserved by Object.assign.
 */
function fixAttributePrototypes(node: XmlNode): void {
  if (node.type !== "element") return;
  if (Object.getPrototypeOf(node.attributes) !== null) {
    const attrs = Object.create(null) as Record<string, string>;
    Object.assign(attrs, node.attributes);
    (node as { attributes: Record<string, string> }).attributes = attrs;
  }
  for (const child of node.children) {
    fixAttributePrototypes(child);
  }
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

const POSITION_RE = / at line (\d+), column (\d+)$/;

/** Re-throw a wasm `Error` as @std/xml's `XmlSyntaxError`. */
function rethrowAsXmlSyntaxError(error: unknown): never {
  if (error instanceof Error) {
    const match = error.message.match(POSITION_RE);
    if (match) {
      throw new XmlSyntaxError(
        error.message.slice(0, match.index!),
        { line: Number(match[1]), column: Number(match[2]), offset: 0 },
      );
    }
    throw new XmlSyntaxError(error.message, {
      line: 0,
      column: 0,
      offset: 0, // 0/0/0: @std/xml's sentinel for "position unavailable"
    });
  }
  throw error;
}

/**
 * Parses an XML string into a document tree.
 *
 * Drop-in compatible with @std/xml's `parse`: the returned object has the
 * identical shape (`{ declaration?, root }`), and the options follow
 * @std/xml's `ParseOptions`. Supported options: `ignoreWhitespace`,
 * `ignoreComments`, `disallowDoctype` (default true), `maxDepth`,
 * `trackPosition` (default true; affects the declaration's position
 * fields). `maxAttributes` and `xmlVersion` are accepted and ignored.
 *
 * @example Usage
 * ```ts
 * import { parse } from "@stdext/xml";
 * import { assertEquals } from "@std/assert";
 *
 * const doc = parse(`<root id="1"><child/></root>`);
 * assertEquals(doc.root.name.local, "root");
 * assertEquals(doc.root.attributes["id"], "1");
 * ```
 *
 * @param xml The XML string to parse.
 * @param options Options for configuring the parser.
 * @returns The parsed document.
 * @throws {XmlSyntaxError} If the XML is malformed or has no root element.
 */
export function parse(xml: string, options?: ParseOptions): XmlDocument {
  try {
    const doc = wasmParse(xml, options) as XmlDocument;
    fixAttributePrototypes(doc.root);
    return doc;
  } catch (error) {
    rethrowAsXmlSyntaxError(error);
  }
}

/**
 * Serializes a document tree back to an XML string.
 *
 * Drop-in compatible with @std/xml's `stringify`: `indent` pretty-prints,
 * and `declaration` (default `true`) includes the XML declaration when the
 * input document has one.
 *
 * @example Usage
 * ```ts
 * import { parse, stringify } from "@stdext/xml";
 *
 * const doc = parse("<root><child/></root>");
 * stringify(doc);                    // "<root><child/></root>"
 * stringify(doc, { indent: "  " });  // pretty-printed
 * ```
 *
 * @param doc The document tree to serialize.
 * @param options Serialization options.
 * @returns The serialized XML string.
 * @throws {SyntaxError} If the input is not a valid XmlDocument object.
 */
export function stringify(
  doc: XmlDocument,
  options?: StringifyOptions,
): string {
  return wasmStringify(doc, options);
}

/**
 * Validates a document against an XSD schema.
 *
 * Both `document` and `schema` accept either an XML string or the plain
 * document object (the same shape `parse` produces).
 *
 * Returns the Standard Schema `Result` union (https://standardschema.dev):
 *   - success: `{ value: XmlDocument }` — `issues` is undefined (falsy)
 *   - failure: `{ issues: XmlValidationIssue[] }` — no `value`
 *
 * Each issue carries `message` and, best-effort, `path` (the chain of
 * enclosing element names with 0-based indices for repeated siblings),
 * plus `line`/`column` when the validator reports a position. Consumers
 * can apply `@standard-schema/utils` helpers (`getDotPath`, `SchemaError`)
 * directly to the result — the issue shape is the spec's own.
 *
 * Note: a schema that is not well-formed or is an invalid XSD *throws*
 * (`XmlSyntaxError` / `Error`) — that is a schema-authoring error, not a
 * document issue.
 *
 * @example Usage
 * ```ts
 * import { validate } from "@stdext/xml";
 * import { assert } from "@std/assert";
 *
 * const xsd = `<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
 *   <xs:element name="age" type="xs:positiveInteger"/>
 * </xs:schema>`;
 *
 * const result = validate("<age>25</age>", xsd);
 * assert(result.issues === undefined); // success
 * result.value.root.name.local; // "age"
 * ```
 *
 * @param document The document to validate (XML string or document tree).
 * @param schema The XSD schema to validate against (XML string or tree).
 * @returns The Standard Schema result: `{ value }` or `{ issues }`.
 * @throws {XmlSyntaxError} If the document or schema is not well-formed XML.
 * @throws {Error} If the schema is an invalid XSD.
 */
export function validate(
  document: string | XmlDocument,
  schema: string | XmlDocument,
): XmlValidationResult {
  try {
    const result = wasmValidate(document, schema) as XmlValidationResult;
    if (result.issues === undefined) {
      fixAttributePrototypes(result.value.root);
    }
    return result;
  } catch (error) {
    rethrowAsXmlSyntaxError(error);
  }
}

// ---------------------------------------------------------------------------
// Standard Schema facade
// ---------------------------------------------------------------------------

/**
 * Compile an XSD schema into a Standard Schema v1 entity
 * (https://standardschema.dev), so it can be consumed by any
 * Standard Schema-aware tool.
 *
 * The returned object's `~standard.validate(value)` accepts an XML string
 * or an XmlDocument and returns the spec's discriminated result:
 *   - success: `{ value: XmlDocument }` (`issues` is undefined — falsy)
 *   - failure: `{ issues: XmlValidationIssue[] }`
 *
 * Issues carry `message` plus best-effort `path` (enclosing element names,
 * with sibling indices for repeated elements), `line` and `column`.
 *
 * @example Usage
 * ```ts
 * import { compileSchema } from "@stdext/xml";
 * import { assert } from "@std/assert";
 *
 * const schema = compileSchema(`<xs:schema
 *   xmlns:xs="http://www.w3.org/2001/XMLSchema">
 *   <xs:element name="age" type="xs:positiveInteger"/>
 * </xs:schema>`);
 *
 * const result = schema["~standard"].validate("<age>25</age>");
 * assert(!("issues" in result)); // success: result.value is the tree
 * ```
 *
 * @param schema The XSD schema (XML string or document tree).
 * @returns A Standard Schema v1 entity validating against that schema.
 */
export function xsdSchema(
  schema: string | XmlDocument,
): StandardSchemaV1<string | XmlDocument, XmlDocument> {
  return {
    "~standard": {
      version: 1,
      vendor: "@stdext/xml",
      validate: (
        value: unknown,
        _options?: StandardSchemaV1.Options,
      ): StandardSchemaV1.Result<XmlDocument> => {
        if (
          typeof value !== "string" &&
          (!isObject(value) ||
            !("root" in (value as Record<string, unknown>)))
        ) {
          return {
            issues: [
              {
                message: "expected an XML string or an XmlDocument object",
              },
            ],
          };
        }
        // `validate` already returns the spec's Result union — pass it
        // through unchanged.
        return validate(value as string | XmlDocument, schema);
      },
    },
  };
}
