[package]
name = "dom_domparser"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen.workspace = true
serde.workspace = true
serde-wasm-bindgen.workspace = true
html5ever = "0.26"
markup5ever_rcdom = "0.2"
tendril = "0.4"
quick-xml = { version = "0.31", features = ["serialize"] }
