[package]
name = "dom_domparser"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen.workspace = true
serde.workspace = true
serde-wasm-bindgen.workspace = true
js-sys = "0.3"
web-sys = { version = "0.3", features = ["Document", "DomParser", "Node", "Element", "HtmlElement", "Text", "Comment", "DocumentFragment", "DocumentType", "Attr", "NamedNodeMap", "NodeList", "HtmlCollection", "DomTokenList", "HtmlHeadElement", "HtmlBodyElement", "HtmlTitleElement", "HtmlMetaElement", "HtmlLinkElement", "HtmlScriptElement", "HtmlStyleElement"] }
