[package]
name = "deno_stdext_crypto_hash_wasm_bcrypt"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen.workspace = true
serde.workspace = true
serde-wasm-bindgen.workspace = true
getrandom.workspace = true
bcrypt.workspace = true
