name: workspace publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: canary

      - name: Format & Lint
        run: deno task check

      - name: Build
        run: deno task build:wasm:check

      - name: Test
        run: deno task test

      - name: Publish to JSR
        run: deno publish
